/**
 * This class is generated by jOOQ
 */
package jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.tables.Company;
import jooq.tables.Image;
import jooq.tables.Job;
import jooq.tables.JobApplication;
import jooq.tables.JobInterview;
import jooq.tables.JobOffer;
import jooq.tables.Location;
import jooq.tables.School;
import jooq.tables.Student;
import jooq.tables.User;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

	private static final long serialVersionUID = -1491589567;

	/**
	 * The reference instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.COMPANY_ID_SEQ,
			Sequences.JOB_POSTING_JOBPOSTINGID_SEQ,
			Sequences.SCHOOL_SCHOOLD_SEQ,
			Sequences.STUDENT_ID_SEQ);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Company.COMPANY,
			Image.IMAGE,
			Job.JOB,
			JobApplication.JOB_APPLICATION,
			JobInterview.JOB_INTERVIEW,
			JobOffer.JOB_OFFER,
			Location.LOCATION,
			School.SCHOOL,
			Student.STUDENT,
			User.USER);
	}
}
