/**
 * This class is generated by jOOQ
 */
package jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.tables.Company;
import jooq.tables.Document;
import jooq.tables.Image;
import jooq.tables.Job;
import jooq.tables.JobApp;
import jooq.tables.JobAppPackage;
import jooq.tables.JobInterview;
import jooq.tables.JobMine;
import jooq.tables.JobOffer;
import jooq.tables.Location;
import jooq.tables.School;
import jooq.tables.Student;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

	private static final long serialVersionUID = -1704907539;

	/**
	 * The reference instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Company.COMPANY,
			Document.DOCUMENT,
			Image.IMAGE,
			Job.JOB,
			JobApp.JOB_APP,
			JobAppPackage.JOB_APP_PACKAGE,
			JobInterview.JOB_INTERVIEW,
			JobMine.JOB_MINE,
			JobOffer.JOB_OFFER,
			Location.LOCATION,
			School.SCHOOL,
			Student.STUDENT);
	}
}
