/**
 * This class is generated by jOOQ
 */
package jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.job_posting_jobpostingid_seq</code>
	 */
	public static final Sequence<Long> JOB_POSTING_JOBPOSTINGID_SEQ = new SequenceImpl<Long>("job_posting_jobpostingid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.school_schoold_seq</code>
	 */
	public static final Sequence<Long> SCHOOL_SCHOOLD_SEQ = new SequenceImpl<Long>("school_schoold_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.student_id_seq</code>
	 */
	public static final Sequence<Long> STUDENT_ID_SEQ = new SequenceImpl<Long>("student_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
