/**
 * This class is generated by jOOQ
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.Company;
import jooq.tables.Job;
import jooq.tables.School;
import jooq.tables.Student;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.company
	 */
	public static final Company COMPANY = jooq.tables.Company.COMPANY;

	/**
	 * The table public.job
	 */
	public static final Job JOB = jooq.tables.Job.JOB;

	/**
	 * The table public.school
	 */
	public static final School SCHOOL = jooq.tables.School.SCHOOL;

	/**
	 * The table public.student
	 */
	public static final Student STUDENT = jooq.tables.Student.STUDENT;
}
