/**
 * This class is generated by jOOQ
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.Company;
import jooq.tables.Document;
import jooq.tables.Image;
import jooq.tables.Job;
import jooq.tables.JobApp;
import jooq.tables.JobAppPackage;
import jooq.tables.JobInterview;
import jooq.tables.JobMine;
import jooq.tables.JobOffer;
import jooq.tables.Location;
import jooq.tables.School;
import jooq.tables.Student;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.company
	 */
	public static final Company COMPANY = jooq.tables.Company.COMPANY;

	/**
	 * The table public.document
	 */
	public static final Document DOCUMENT = jooq.tables.Document.DOCUMENT;

	/**
	 * The table public.image
	 */
	public static final Image IMAGE = jooq.tables.Image.IMAGE;

	/**
	 * The table public.job
	 */
	public static final Job JOB = jooq.tables.Job.JOB;

	/**
	 * The table public.job_app
	 */
	public static final JobApp JOB_APP = jooq.tables.JobApp.JOB_APP;

	/**
	 * The table public.job_app_package
	 */
	public static final JobAppPackage JOB_APP_PACKAGE = jooq.tables.JobAppPackage.JOB_APP_PACKAGE;

	/**
	 * The table public.job_interview
	 */
	public static final JobInterview JOB_INTERVIEW = jooq.tables.JobInterview.JOB_INTERVIEW;

	/**
	 * The table public.job_mine
	 */
	public static final JobMine JOB_MINE = jooq.tables.JobMine.JOB_MINE;

	/**
	 * The table public.job_offer
	 */
	public static final JobOffer JOB_OFFER = jooq.tables.JobOffer.JOB_OFFER;

	/**
	 * The table public.location
	 */
	public static final Location LOCATION = jooq.tables.Location.LOCATION;

	/**
	 * The table public.school
	 */
	public static final School SCHOOL = jooq.tables.School.SCHOOL;

	/**
	 * The table public.student
	 */
	public static final Student STUDENT = jooq.tables.Student.STUDENT;
}
