/**
 * This class is generated by jOOQ
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Company implements Serializable {

	private static final long serialVersionUID = 683033526;

	private final Integer companyId;
	private final String  name;
	private final String  logourl;

	public Company(Company value) {
		this.companyId = value.companyId;
		this.name = value.name;
		this.logourl = value.logourl;
	}

	public Company(
		Integer companyId,
		String  name,
		String  logourl
	) {
		this.companyId = companyId;
		this.name = name;
		this.logourl = logourl;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public String getName() {
		return this.name;
	}

	public String getLogourl() {
		return this.logourl;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Company (");

		sb.append(companyId);
		sb.append(", ").append(name);
		sb.append(", ").append(logourl);

		sb.append(")");
		return sb.toString();
	}
}
