/**
 * This class is generated by jOOQ
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Company implements Serializable {

	private static final long serialVersionUID = 1827224785;

	private final Integer id;
	private final String  name;
	private final String  logourl;

	public Company(Company value) {
		this.id = value.id;
		this.name = value.name;
		this.logourl = value.logourl;
	}

	public Company(
		Integer id,
		String  name,
		String  logourl
	) {
		this.id = id;
		this.name = name;
		this.logourl = logourl;
	}

	public Integer getId() {
		return this.id;
	}

	public String getName() {
		return this.name;
	}

	public String getLogourl() {
		return this.logourl;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Company (");

		sb.append(id);
		sb.append(", ").append(name);
		sb.append(", ").append(logourl);

		sb.append(")");
		return sb.toString();
	}
}
