/**
 * This class is generated by jOOQ
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Group implements Serializable {

	private static final long serialVersionUID = 266374533;

	private final Integer groupId;

	public Group(Group value) {
		this.groupId = value.groupId;
	}

	public Group(
		Integer groupId
	) {
		this.groupId = groupId;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Group (");

		sb.append(groupId);

		sb.append(")");
		return sb.toString();
	}
}
