/**
 * This class is generated by jOOQ
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobApplication implements Serializable {

	private static final long serialVersionUID = -780022907;

	private final Integer jobApplicationId;

	public JobApplication(JobApplication value) {
		this.jobApplicationId = value.jobApplicationId;
	}

	public JobApplication(
		Integer jobApplicationId
	) {
		this.jobApplicationId = jobApplicationId;
	}

	public Integer getJobApplicationId() {
		return this.jobApplicationId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("JobApplication (");

		sb.append(jobApplicationId);

		sb.append(")");
		return sb.toString();
	}
}
