/**
 * This class is generated by jOOQ
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobInterview implements Serializable {

	private static final long serialVersionUID = 327917729;

	private final Integer jobInterviewId;

	public JobInterview(JobInterview value) {
		this.jobInterviewId = value.jobInterviewId;
	}

	public JobInterview(
		Integer jobInterviewId
	) {
		this.jobInterviewId = jobInterviewId;
	}

	public Integer getJobInterviewId() {
		return this.jobInterviewId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("JobInterview (");

		sb.append(jobInterviewId);

		sb.append(")");
		return sb.toString();
	}
}
