/**
 * This class is generated by jOOQ
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobMine implements Serializable {

	private static final long serialVersionUID = 72629192;

	private final Integer jobMineId;
	private final String  name;
	private final Integer schoolId;

	public JobMine(JobMine value) {
		this.jobMineId = value.jobMineId;
		this.name = value.name;
		this.schoolId = value.schoolId;
	}

	public JobMine(
		Integer jobMineId,
		String  name,
		Integer schoolId
	) {
		this.jobMineId = jobMineId;
		this.name = name;
		this.schoolId = schoolId;
	}

	public Integer getJobMineId() {
		return this.jobMineId;
	}

	public String getName() {
		return this.name;
	}

	public Integer getSchoolId() {
		return this.schoolId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("JobMine (");

		sb.append(jobMineId);
		sb.append(", ").append(name);
		sb.append(", ").append(schoolId);

		sb.append(")");
		return sb.toString();
	}
}
