/**
 * This class is generated by jOOQ
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobOffer implements Serializable {

	private static final long serialVersionUID = 1088144853;

	private final Integer jobOfferId;

	public JobOffer(JobOffer value) {
		this.jobOfferId = value.jobOfferId;
	}

	public JobOffer(
		Integer jobOfferId
	) {
		this.jobOfferId = jobOfferId;
	}

	public Integer getJobOfferId() {
		return this.jobOfferId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("JobOffer (");

		sb.append(jobOfferId);

		sb.append(")");
		return sb.toString();
	}
}
