/**
 * This class is generated by jOOQ
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Location implements Serializable {

	private static final long serialVersionUID = -1478056003;

	private final Integer locationId;

	public Location(Location value) {
		this.locationId = value.locationId;
	}

	public Location(
		Integer locationId
	) {
		this.locationId = locationId;
	}

	public Integer getLocationId() {
		return this.locationId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Location (");

		sb.append(locationId);

		sb.append(")");
		return sb.toString();
	}
}
