/**
 * This class is generated by jOOQ
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class School implements Serializable {

	private static final long serialVersionUID = -952103966;

	private final Integer schoold;
	private final String  name;
	private final String  schooltype;
	private final String  city;
	private final String  provinceorstate;
	private final String  established;
	private final Integer totalstudents;
	private final String  wikilink;
	private final String  logosrc;
	private final String  country;

	public School(School value) {
		this.schoold = value.schoold;
		this.name = value.name;
		this.schooltype = value.schooltype;
		this.city = value.city;
		this.provinceorstate = value.provinceorstate;
		this.established = value.established;
		this.totalstudents = value.totalstudents;
		this.wikilink = value.wikilink;
		this.logosrc = value.logosrc;
		this.country = value.country;
	}

	public School(
		Integer schoold,
		String  name,
		String  schooltype,
		String  city,
		String  provinceorstate,
		String  established,
		Integer totalstudents,
		String  wikilink,
		String  logosrc,
		String  country
	) {
		this.schoold = schoold;
		this.name = name;
		this.schooltype = schooltype;
		this.city = city;
		this.provinceorstate = provinceorstate;
		this.established = established;
		this.totalstudents = totalstudents;
		this.wikilink = wikilink;
		this.logosrc = logosrc;
		this.country = country;
	}

	public Integer getSchoold() {
		return this.schoold;
	}

	public String getName() {
		return this.name;
	}

	public String getSchooltype() {
		return this.schooltype;
	}

	public String getCity() {
		return this.city;
	}

	public String getProvinceorstate() {
		return this.provinceorstate;
	}

	public String getEstablished() {
		return this.established;
	}

	public Integer getTotalstudents() {
		return this.totalstudents;
	}

	public String getWikilink() {
		return this.wikilink;
	}

	public String getLogosrc() {
		return this.logosrc;
	}

	public String getCountry() {
		return this.country;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("School (");

		sb.append(schoold);
		sb.append(", ").append(name);
		sb.append(", ").append(schooltype);
		sb.append(", ").append(city);
		sb.append(", ").append(provinceorstate);
		sb.append(", ").append(established);
		sb.append(", ").append(totalstudents);
		sb.append(", ").append(wikilink);
		sb.append(", ").append(logosrc);
		sb.append(", ").append(country);

		sb.append(")");
		return sb.toString();
	}
}
