/**
 * This class is generated by jOOQ
 */
package jooq.tables.records;


import javax.annotation.Generated;

import jooq.tables.Company;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyRecord extends UpdatableRecordImpl<CompanyRecord> implements Record3<Integer, String, String> {

	private static final long serialVersionUID = -1347695157;

	/**
	 * Setter for <code>public.company.company_id</code>.
	 */
	public CompanyRecord setCompanyId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.company.company_id</code>.
	 */
	public Integer getCompanyId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.company.name</code>.
	 */
	public CompanyRecord setName(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.company.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.company.logourl</code>.
	 */
	public CompanyRecord setLogourl(String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.company.logourl</code>.
	 */
	public String getLogourl() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Company.COMPANY.COMPANY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Company.COMPANY.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Company.COMPANY.LOGOURL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getCompanyId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getLogourl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompanyRecord value1(Integer value) {
		setCompanyId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompanyRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompanyRecord value3(String value) {
		setLogourl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompanyRecord values(Integer value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CompanyRecord
	 */
	public CompanyRecord() {
		super(Company.COMPANY);
	}

	/**
	 * Create a detached, initialised CompanyRecord
	 */
	public CompanyRecord(Integer companyId, String name, String logourl) {
		super(Company.COMPANY);

		setValue(0, companyId);
		setValue(1, name);
		setValue(2, logourl);
	}
}
