/**
 * This class is generated by jOOQ
 */
package jooq.tables.records;


import javax.annotation.Generated;

import jooq.tables.JobApplication;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobApplicationRecord extends TableRecordImpl<JobApplicationRecord> implements Record1<Integer> {

	private static final long serialVersionUID = 1413758395;

	/**
	 * Setter for <code>public.job_application.job_application_id</code>.
	 */
	public JobApplicationRecord setJobApplicationId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.job_application.job_application_id</code>.
	 */
	public Integer getJobApplicationId() {
		return (Integer) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<Integer> fieldsRow() {
		return (Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<Integer> valuesRow() {
		return (Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return JobApplication.JOB_APPLICATION.JOB_APPLICATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getJobApplicationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobApplicationRecord value1(Integer value) {
		setJobApplicationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobApplicationRecord values(Integer value1) {
		value1(value1);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JobApplicationRecord
	 */
	public JobApplicationRecord() {
		super(JobApplication.JOB_APPLICATION);
	}

	/**
	 * Create a detached, initialised JobApplicationRecord
	 */
	public JobApplicationRecord(Integer jobApplicationId) {
		super(JobApplication.JOB_APPLICATION);

		setValue(0, jobApplicationId);
	}
}
