/**
 * This class is generated by jOOQ
 */
package jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jooq.tables.JobInterview;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobInterviewRecord extends UpdatableRecordImpl<JobInterviewRecord> implements Record5<Integer, String, Timestamp, Integer, Integer> {

	private static final long serialVersionUID = 1568410722;

	/**
	 * Setter for <code>public.job_interview.job_interview_id</code>.
	 */
	public JobInterviewRecord setJobInterviewId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.job_interview.job_interview_id</code>.
	 */
	public Integer getJobInterviewId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.job_interview.status</code>.
	 */
	public JobInterviewRecord setStatus(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.job_interview.status</code>.
	 */
	public String getStatus() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.job_interview.created_timestamp</code>.
	 */
	public JobInterviewRecord setCreatedTimestamp(Timestamp value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.job_interview.created_timestamp</code>.
	 */
	public Timestamp getCreatedTimestamp() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>public.job_interview.job_id</code>.
	 */
	public JobInterviewRecord setJobId(Integer value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.job_interview.job_id</code>.
	 */
	public Integer getJobId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.job_interview.student_id</code>.
	 */
	public JobInterviewRecord setStudentId(Integer value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.job_interview.student_id</code>.
	 */
	public Integer getStudentId() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, Timestamp, Integer, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, Timestamp, Integer, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return JobInterview.JOB_INTERVIEW.JOB_INTERVIEW_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return JobInterview.JOB_INTERVIEW.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return JobInterview.JOB_INTERVIEW.CREATED_TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return JobInterview.JOB_INTERVIEW.JOB_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return JobInterview.JOB_INTERVIEW.STUDENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getJobInterviewId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getCreatedTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getJobId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getStudentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobInterviewRecord value1(Integer value) {
		setJobInterviewId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobInterviewRecord value2(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobInterviewRecord value3(Timestamp value) {
		setCreatedTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobInterviewRecord value4(Integer value) {
		setJobId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobInterviewRecord value5(Integer value) {
		setStudentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobInterviewRecord values(Integer value1, String value2, Timestamp value3, Integer value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JobInterviewRecord
	 */
	public JobInterviewRecord() {
		super(JobInterview.JOB_INTERVIEW);
	}

	/**
	 * Create a detached, initialised JobInterviewRecord
	 */
	public JobInterviewRecord(Integer jobInterviewId, String status, Timestamp createdTimestamp, Integer jobId, Integer studentId) {
		super(JobInterview.JOB_INTERVIEW);

		setValue(0, jobInterviewId);
		setValue(1, status);
		setValue(2, createdTimestamp);
		setValue(3, jobId);
		setValue(4, studentId);
	}
}
