/**
 * This class is generated by jOOQ
 */
package jooq.tables.records;


import javax.annotation.Generated;

import jooq.tables.JobInterview;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobInterviewRecord extends TableRecordImpl<JobInterviewRecord> implements Record1<Integer> {

	private static final long serialVersionUID = -884599212;

	/**
	 * Setter for <code>public.job_interview.job_interview_id</code>.
	 */
	public JobInterviewRecord setJobInterviewId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.job_interview.job_interview_id</code>.
	 */
	public Integer getJobInterviewId() {
		return (Integer) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<Integer> fieldsRow() {
		return (Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<Integer> valuesRow() {
		return (Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return JobInterview.JOB_INTERVIEW.JOB_INTERVIEW_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getJobInterviewId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobInterviewRecord value1(Integer value) {
		setJobInterviewId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobInterviewRecord values(Integer value1) {
		value1(value1);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JobInterviewRecord
	 */
	public JobInterviewRecord() {
		super(JobInterview.JOB_INTERVIEW);
	}

	/**
	 * Create a detached, initialised JobInterviewRecord
	 */
	public JobInterviewRecord(Integer jobInterviewId) {
		super(JobInterview.JOB_INTERVIEW);

		setValue(0, jobInterviewId);
	}
}
