/**
 * This class is generated by jOOQ
 */
package jooq.tables.records;


import javax.annotation.Generated;

import jooq.tables.JobOffer;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobOfferRecord extends TableRecordImpl<JobOfferRecord> implements Record1<Integer> {

	private static final long serialVersionUID = -1734295257;

	/**
	 * Setter for <code>public.job_offer.job_offer_id</code>.
	 */
	public JobOfferRecord setJobOfferId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.job_offer.job_offer_id</code>.
	 */
	public Integer getJobOfferId() {
		return (Integer) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<Integer> fieldsRow() {
		return (Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<Integer> valuesRow() {
		return (Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return JobOffer.JOB_OFFER.JOB_OFFER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getJobOfferId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobOfferRecord value1(Integer value) {
		setJobOfferId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobOfferRecord values(Integer value1) {
		value1(value1);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JobOfferRecord
	 */
	public JobOfferRecord() {
		super(JobOffer.JOB_OFFER);
	}

	/**
	 * Create a detached, initialised JobOfferRecord
	 */
	public JobOfferRecord(Integer jobOfferId) {
		super(JobOffer.JOB_OFFER);

		setValue(0, jobOfferId);
	}
}
