/**
 * This class is generated by jOOQ
 */
package jooq.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import jooq.tables.Job;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobRecord extends UpdatableRecordImpl<JobRecord> implements Record7<Integer, String, String, String, Date, String, byte[]> {

	private static final long serialVersionUID = -1795153825;

	/**
	 * Setter for <code>public.job.jobpostingid</code>.
	 */
	public JobRecord setJobpostingid(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.job.jobpostingid</code>.
	 */
	public Integer getJobpostingid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.job.title</code>.
	 */
	public JobRecord setTitle(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.job.title</code>.
	 */
	public String getTitle() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.job.description	</code>.
	 */
	public JobRecord setDescription_9(String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.job.description	</code>.
	 */
	public String getDescription_9() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.job.location</code>.
	 */
	public JobRecord setLocation(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.job.location</code>.
	 */
	public String getLocation() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.job.datePosted	</code>.
	 */
	public JobRecord setDateposted_9(Date value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.job.datePosted	</code>.
	 */
	public Date getDateposted_9() {
		return (Date) getValue(4);
	}

	/**
	 * Setter for <code>public.job.employername</code>.
	 */
	public JobRecord setEmployername(String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.job.employername</code>.
	 */
	public String getEmployername() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.job.employerlogo</code>.
	 */
	public JobRecord setEmployerlogo(byte[] value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>public.job.employerlogo</code>.
	 */
	public byte[] getEmployerlogo() {
		return (byte[]) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, String, String, String, Date, String, byte[]> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, String, String, String, Date, String, byte[]> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Job.JOB.JOBPOSTINGID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Job.JOB.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Job.JOB.DESCRIPTION_9;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Job.JOB.LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field5() {
		return Job.JOB.DATEPOSTED_9;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Job.JOB.EMPLOYERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<byte[]> field7() {
		return Job.JOB.EMPLOYERLOGO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getJobpostingid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getDescription_9();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value5() {
		return getDateposted_9();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getEmployername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value7() {
		return getEmployerlogo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobRecord value1(Integer value) {
		setJobpostingid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobRecord value2(String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobRecord value3(String value) {
		setDescription_9(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobRecord value4(String value) {
		setLocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobRecord value5(Date value) {
		setDateposted_9(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobRecord value6(String value) {
		setEmployername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobRecord value7(byte[] value) {
		setEmployerlogo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobRecord values(Integer value1, String value2, String value3, String value4, Date value5, String value6, byte[] value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JobRecord
	 */
	public JobRecord() {
		super(Job.JOB);
	}

	/**
	 * Create a detached, initialised JobRecord
	 */
	public JobRecord(Integer jobpostingid, String title, String description_9, String location, Date dateposted_9, String employername, byte[] employerlogo) {
		super(Job.JOB);

		setValue(0, jobpostingid);
		setValue(1, title);
		setValue(2, description_9);
		setValue(3, location);
		setValue(4, dateposted_9);
		setValue(5, employername);
		setValue(6, employerlogo);
	}
}
