/**
 * This class is generated by jOOQ
 */
package jooq.tables;


import javax.annotation.Generated;

import jooq.Public;
import jooq.tables.records.ImageRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Image extends TableImpl<ImageRecord> {

	private static final long serialVersionUID = 645975392;

	/**
	 * The reference instance of <code>public.image</code>
	 */
	public static final Image IMAGE = new Image();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ImageRecord> getRecordType() {
		return ImageRecord.class;
	}

	/**
	 * The column <code>public.image.image_id</code>.
	 */
	public final TableField<ImageRecord, Integer> IMAGE_ID = createField("image_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.image</code> table reference
	 */
	public Image() {
		this("image", null);
	}

	/**
	 * Create an aliased <code>public.image</code> table reference
	 */
	public Image(String alias) {
		this(alias, IMAGE);
	}

	private Image(String alias, Table<ImageRecord> aliased) {
		this(alias, aliased, null);
	}

	private Image(String alias, Table<ImageRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Image as(String alias) {
		return new Image(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Image rename(String name) {
		return new Image(name, null);
	}
}
