/**
 * This class is generated by jOOQ
 */
package jooq.tables;


import javax.annotation.Generated;

import jooq.Public;
import jooq.tables.records.JobApplicationRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobApplication extends TableImpl<JobApplicationRecord> {

	private static final long serialVersionUID = -1551796646;

	/**
	 * The reference instance of <code>public.job_application</code>
	 */
	public static final JobApplication JOB_APPLICATION = new JobApplication();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<JobApplicationRecord> getRecordType() {
		return JobApplicationRecord.class;
	}

	/**
	 * The column <code>public.job_application.job_application_id</code>.
	 */
	public final TableField<JobApplicationRecord, Integer> JOB_APPLICATION_ID = createField("job_application_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.job_application</code> table reference
	 */
	public JobApplication() {
		this("job_application", null);
	}

	/**
	 * Create an aliased <code>public.job_application</code> table reference
	 */
	public JobApplication(String alias) {
		this(alias, JOB_APPLICATION);
	}

	private JobApplication(String alias, Table<JobApplicationRecord> aliased) {
		this(alias, aliased, null);
	}

	private JobApplication(String alias, Table<JobApplicationRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobApplication as(String alias) {
		return new JobApplication(alias, this);
	}

	/**
	 * Rename this table
	 */
	public JobApplication rename(String name) {
		return new JobApplication(name, null);
	}
}
