/**
 * This class is generated by jOOQ
 */
package jooq.tables;


import javax.annotation.Generated;

import jooq.Public;
import jooq.tables.records.JobInterviewRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobInterview extends TableImpl<JobInterviewRecord> {

	private static final long serialVersionUID = 1973764448;

	/**
	 * The reference instance of <code>public.job_interview</code>
	 */
	public static final JobInterview JOB_INTERVIEW = new JobInterview();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<JobInterviewRecord> getRecordType() {
		return JobInterviewRecord.class;
	}

	/**
	 * The column <code>public.job_interview.job_interview_id</code>.
	 */
	public final TableField<JobInterviewRecord, Integer> JOB_INTERVIEW_ID = createField("job_interview_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.job_interview</code> table reference
	 */
	public JobInterview() {
		this("job_interview", null);
	}

	/**
	 * Create an aliased <code>public.job_interview</code> table reference
	 */
	public JobInterview(String alias) {
		this(alias, JOB_INTERVIEW);
	}

	private JobInterview(String alias, Table<JobInterviewRecord> aliased) {
		this(alias, aliased, null);
	}

	private JobInterview(String alias, Table<JobInterviewRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobInterview as(String alias) {
		return new JobInterview(alias, this);
	}

	/**
	 * Rename this table
	 */
	public JobInterview rename(String name) {
		return new JobInterview(name, null);
	}
}
