/**
 * This class is generated by jOOQ
 */
package jooq.tables;


import javax.annotation.Generated;

import jooq.Public;
import jooq.tables.records.JobOfferRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobOffer extends TableImpl<JobOfferRecord> {

	private static final long serialVersionUID = 1836007586;

	/**
	 * The reference instance of <code>public.job_offer</code>
	 */
	public static final JobOffer JOB_OFFER = new JobOffer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<JobOfferRecord> getRecordType() {
		return JobOfferRecord.class;
	}

	/**
	 * The column <code>public.job_offer.job_offer_id</code>.
	 */
	public final TableField<JobOfferRecord, Integer> JOB_OFFER_ID = createField("job_offer_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.job_offer</code> table reference
	 */
	public JobOffer() {
		this("job_offer", null);
	}

	/**
	 * Create an aliased <code>public.job_offer</code> table reference
	 */
	public JobOffer(String alias) {
		this(alias, JOB_OFFER);
	}

	private JobOffer(String alias, Table<JobOfferRecord> aliased) {
		this(alias, aliased, null);
	}

	private JobOffer(String alias, Table<JobOfferRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobOffer as(String alias) {
		return new JobOffer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public JobOffer rename(String name) {
		return new JobOffer(name, null);
	}
}
