/**
 * This class is generated by jOOQ
 */
package jooq.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.Keys;
import jooq.Public;
import jooq.tables.records.JobPostingRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobPosting extends TableImpl<JobPostingRecord> {

	private static final long serialVersionUID = 1098112417;

	/**
	 * The reference instance of <code>public.job_posting</code>
	 */
	public static final JobPosting JOB_POSTING = new JobPosting();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<JobPostingRecord> getRecordType() {
		return JobPostingRecord.class;
	}

	/**
	 * The column <code>public.job_posting.jobpostingid</code>.
	 */
	public final TableField<JobPostingRecord, Integer> JOBPOSTINGID = createField("jobpostingid", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.job_posting.title</code>.
	 */
	public final TableField<JobPostingRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.job_posting.description	</code>.
	 */
	public final TableField<JobPostingRecord, String> DESCRIPTION_9 = createField("description	", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.job_posting.location</code>.
	 */
	public final TableField<JobPostingRecord, String> LOCATION = createField("location", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.job_posting.datePosted	</code>.
	 */
	public final TableField<JobPostingRecord, Date> DATEPOSTED_9 = createField("datePosted	", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>public.job_posting.employername</code>.
	 */
	public final TableField<JobPostingRecord, String> EMPLOYERNAME = createField("employername", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.job_posting.employerlogo</code>.
	 */
	public final TableField<JobPostingRecord, byte[]> EMPLOYERLOGO = createField("employerlogo", org.jooq.impl.SQLDataType.BLOB, this, "");

	/**
	 * Create a <code>public.job_posting</code> table reference
	 */
	public JobPosting() {
		this("job_posting", null);
	}

	/**
	 * Create an aliased <code>public.job_posting</code> table reference
	 */
	public JobPosting(String alias) {
		this(alias, JOB_POSTING);
	}

	private JobPosting(String alias, Table<JobPostingRecord> aliased) {
		this(alias, aliased, null);
	}

	private JobPosting(String alias, Table<JobPostingRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<JobPostingRecord, Integer> getIdentity() {
		return Keys.IDENTITY_JOB_POSTING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<JobPostingRecord> getPrimaryKey() {
		return Keys.JOB_POSTING_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<JobPostingRecord>> getKeys() {
		return Arrays.<UniqueKey<JobPostingRecord>>asList(Keys.JOB_POSTING_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JobPosting as(String alias) {
		return new JobPosting(alias, this);
	}

	/**
	 * Rename this table
	 */
	public JobPosting rename(String name) {
		return new JobPosting(name, null);
	}
}
