/**
 * This class is generated by jOOQ
 */
package jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.Keys;
import jooq.Public;
import jooq.tables.records.SchoolRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class School extends TableImpl<SchoolRecord> {

	private static final long serialVersionUID = 1763713424;

	/**
	 * The reference instance of <code>public.school</code>
	 */
	public static final School SCHOOL = new School();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SchoolRecord> getRecordType() {
		return SchoolRecord.class;
	}

	/**
	 * The column <code>public.school.school_id</code>.
	 */
	public final TableField<SchoolRecord, Integer> SCHOOL_ID = createField("school_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.school.name</code>.
	 */
	public final TableField<SchoolRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.school.schooltype</code>.
	 */
	public final TableField<SchoolRecord, String> SCHOOLTYPE = createField("schooltype", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.school.city</code>.
	 */
	public final TableField<SchoolRecord, String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.school.provinceorstate</code>.
	 */
	public final TableField<SchoolRecord, String> PROVINCEORSTATE = createField("provinceorstate", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.school.established</code>.
	 */
	public final TableField<SchoolRecord, String> ESTABLISHED = createField("established", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.school.totalstudents</code>.
	 */
	public final TableField<SchoolRecord, Integer> TOTALSTUDENTS = createField("totalstudents", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.school.wikilink</code>.
	 */
	public final TableField<SchoolRecord, String> WIKILINK = createField("wikilink", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.school.logosrc</code>.
	 */
	public final TableField<SchoolRecord, String> LOGOSRC = createField("logosrc", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.school.country</code>.
	 */
	public final TableField<SchoolRecord, String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.school</code> table reference
	 */
	public School() {
		this("school", null);
	}

	/**
	 * Create an aliased <code>public.school</code> table reference
	 */
	public School(String alias) {
		this(alias, SCHOOL);
	}

	private School(String alias, Table<SchoolRecord> aliased) {
		this(alias, aliased, null);
	}

	private School(String alias, Table<SchoolRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<SchoolRecord, Integer> getIdentity() {
		return Keys.IDENTITY_SCHOOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SchoolRecord> getPrimaryKey() {
		return Keys.SCHOOL_SCHOOLD_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SchoolRecord>> getKeys() {
		return Arrays.<UniqueKey<SchoolRecord>>asList(Keys.SCHOOL_SCHOOLD_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public School as(String alias) {
		return new School(alias, this);
	}

	/**
	 * Rename this table
	 */
	public School rename(String name) {
		return new School(name, null);
	}
}
