/**
 * This class is generated by jOOQ
 */
package jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import jooq.tables.Company;
import jooq.tables.records.CompanyRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyDao extends DAOImpl<CompanyRecord, jooq.tables.pojos.Company, Integer> {

	/**
	 * Create a new CompanyDao without any configuration
	 */
	public CompanyDao() {
		super(Company.COMPANY, jooq.tables.pojos.Company.class);
	}

	/**
	 * Create a new CompanyDao with an attached configuration
	 */
	public CompanyDao(Configuration configuration) {
		super(Company.COMPANY, jooq.tables.pojos.Company.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(jooq.tables.pojos.Company object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<jooq.tables.pojos.Company> fetchById(Integer... values) {
		return fetch(Company.COMPANY.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public jooq.tables.pojos.Company fetchOneById(Integer value) {
		return fetchOne(Company.COMPANY.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<jooq.tables.pojos.Company> fetchByName(String... values) {
		return fetch(Company.COMPANY.NAME, values);
	}

	/**
	 * Fetch records that have <code>logourl IN (values)</code>
	 */
	public List<jooq.tables.pojos.Company> fetchByLogourl(String... values) {
		return fetch(Company.COMPANY.LOGOURL, values);
	}
}
