/**
 * This class is generated by jOOQ
 */
package jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import jooq.tables.JobApp;
import jooq.tables.records.JobAppRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobAppDao extends DAOImpl<JobAppRecord, jooq.tables.pojos.JobApp, Integer> {

	/**
	 * Create a new JobAppDao without any configuration
	 */
	public JobAppDao() {
		super(JobApp.JOB_APP, jooq.tables.pojos.JobApp.class);
	}

	/**
	 * Create a new JobAppDao with an attached configuration
	 */
	public JobAppDao(Configuration configuration) {
		super(JobApp.JOB_APP, jooq.tables.pojos.JobApp.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(jooq.tables.pojos.JobApp object) {
		return object.getJobAppId();
	}

	/**
	 * Fetch records that have <code>job_app_id IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobApp> fetchByJobAppId(Integer... values) {
		return fetch(JobApp.JOB_APP.JOB_APP_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>job_app_id = value</code>
	 */
	public jooq.tables.pojos.JobApp fetchOneByJobAppId(Integer value) {
		return fetchOne(JobApp.JOB_APP.JOB_APP_ID, value);
	}

	/**
	 * Fetch records that have <code>job_id IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobApp> fetchByJobId(Integer... values) {
		return fetch(JobApp.JOB_APP.JOB_ID, values);
	}

	/**
	 * Fetch records that have <code>job_app_package_id IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobApp> fetchByJobAppPackageId(Integer... values) {
		return fetch(JobApp.JOB_APP.JOB_APP_PACKAGE_ID, values);
	}
}
