/**
 * This class is generated by jOOQ
 */
package jooq.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import jooq.tables.JobInterview;
import jooq.tables.records.JobInterviewRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobInterviewDao extends DAOImpl<JobInterviewRecord, jooq.tables.pojos.JobInterview, Integer> {

	/**
	 * Create a new JobInterviewDao without any configuration
	 */
	public JobInterviewDao() {
		super(JobInterview.JOB_INTERVIEW, jooq.tables.pojos.JobInterview.class);
	}

	/**
	 * Create a new JobInterviewDao with an attached configuration
	 */
	public JobInterviewDao(Configuration configuration) {
		super(JobInterview.JOB_INTERVIEW, jooq.tables.pojos.JobInterview.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(jooq.tables.pojos.JobInterview object) {
		return object.getJobInterviewId();
	}

	/**
	 * Fetch records that have <code>job_interview_id IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobInterview> fetchByJobInterviewId(Integer... values) {
		return fetch(JobInterview.JOB_INTERVIEW.JOB_INTERVIEW_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>job_interview_id = value</code>
	 */
	public jooq.tables.pojos.JobInterview fetchOneByJobInterviewId(Integer value) {
		return fetchOne(JobInterview.JOB_INTERVIEW.JOB_INTERVIEW_ID, value);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobInterview> fetchByStatus(String... values) {
		return fetch(JobInterview.JOB_INTERVIEW.STATUS, values);
	}

	/**
	 * Fetch records that have <code>created_timestamp IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobInterview> fetchByCreatedTimestamp(Timestamp... values) {
		return fetch(JobInterview.JOB_INTERVIEW.CREATED_TIMESTAMP, values);
	}

	/**
	 * Fetch records that have <code>job_id IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobInterview> fetchByJobId(Integer... values) {
		return fetch(JobInterview.JOB_INTERVIEW.JOB_ID, values);
	}

	/**
	 * Fetch records that have <code>student_id IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobInterview> fetchByStudentId(Integer... values) {
		return fetch(JobInterview.JOB_INTERVIEW.STUDENT_ID, values);
	}
}
