/**
 * This class is generated by jOOQ
 */
package jooq.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import jooq.tables.JobMine;
import jooq.tables.records.JobMineRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobMineDao extends DAOImpl<JobMineRecord, jooq.tables.pojos.JobMine, Integer> {

	/**
	 * Create a new JobMineDao without any configuration
	 */
	public JobMineDao() {
		super(JobMine.JOB_MINE, jooq.tables.pojos.JobMine.class);
	}

	/**
	 * Create a new JobMineDao with an attached configuration
	 */
	public JobMineDao(Configuration configuration) {
		super(JobMine.JOB_MINE, jooq.tables.pojos.JobMine.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(jooq.tables.pojos.JobMine object) {
		return object.getJobMineId();
	}

	/**
	 * Fetch records that have <code>job_mine_id IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobMine> fetchByJobMineId(Integer... values) {
		return fetch(JobMine.JOB_MINE.JOB_MINE_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>job_mine_id = value</code>
	 */
	public jooq.tables.pojos.JobMine fetchOneByJobMineId(Integer value) {
		return fetchOne(JobMine.JOB_MINE.JOB_MINE_ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobMine> fetchByName(String... values) {
		return fetch(JobMine.JOB_MINE.NAME, values);
	}

	/**
	 * Fetch records that have <code>school_id IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobMine> fetchBySchoolId(Integer... values) {
		return fetch(JobMine.JOB_MINE.SCHOOL_ID, values);
	}
}
