/**
 * This class is generated by jOOQ
 */
package jooq.tables.daos;


import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import jooq.tables.JobPosting;
import jooq.tables.records.JobPostingRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobPostingDao extends DAOImpl<JobPostingRecord, jooq.tables.pojos.JobPosting, Integer> {

	/**
	 * Create a new JobPostingDao without any configuration
	 */
	public JobPostingDao() {
		super(JobPosting.JOB_POSTING, jooq.tables.pojos.JobPosting.class);
	}

	/**
	 * Create a new JobPostingDao with an attached configuration
	 */
	public JobPostingDao(Configuration configuration) {
		super(JobPosting.JOB_POSTING, jooq.tables.pojos.JobPosting.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(jooq.tables.pojos.JobPosting object) {
		return object.getJobpostingid();
	}

	/**
	 * Fetch records that have <code>jobpostingid IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobPosting> fetchByJobpostingid(Integer... values) {
		return fetch(JobPosting.JOB_POSTING.JOBPOSTINGID, values);
	}

	/**
	 * Fetch a unique record that has <code>jobpostingid = value</code>
	 */
	public jooq.tables.pojos.JobPosting fetchOneByJobpostingid(Integer value) {
		return fetchOne(JobPosting.JOB_POSTING.JOBPOSTINGID, value);
	}

	/**
	 * Fetch records that have <code>title IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobPosting> fetchByTitle(String... values) {
		return fetch(JobPosting.JOB_POSTING.TITLE, values);
	}

	/**
	 * Fetch records that have <code>description	 IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobPosting> fetchByDescription_9(String... values) {
		return fetch(JobPosting.JOB_POSTING.DESCRIPTION_9, values);
	}

	/**
	 * Fetch records that have <code>location IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobPosting> fetchByLocation(String... values) {
		return fetch(JobPosting.JOB_POSTING.LOCATION, values);
	}

	/**
	 * Fetch records that have <code>datePosted	 IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobPosting> fetchByDateposted_9(Date... values) {
		return fetch(JobPosting.JOB_POSTING.DATEPOSTED_9, values);
	}

	/**
	 * Fetch records that have <code>employername IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobPosting> fetchByEmployername(String... values) {
		return fetch(JobPosting.JOB_POSTING.EMPLOYERNAME, values);
	}

	/**
	 * Fetch records that have <code>employerlogo IN (values)</code>
	 */
	public List<jooq.tables.pojos.JobPosting> fetchByEmployerlogo(byte[]... values) {
		return fetch(JobPosting.JOB_POSTING.EMPLOYERLOGO, values);
	}
}
