/**
 * This class is generated by jOOQ
 */
package jooq.tables.daos;


import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import jooq.tables.School;
import jooq.tables.records.SchoolRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchoolDao extends DAOImpl<SchoolRecord, jooq.tables.pojos.School, Integer> {

	/**
	 * Create a new SchoolDao without any configuration
	 */
	public SchoolDao() {
		super(School.SCHOOL, jooq.tables.pojos.School.class);
	}

	/**
	 * Create a new SchoolDao with an attached configuration
	 */
	public SchoolDao(Configuration configuration) {
		super(School.SCHOOL, jooq.tables.pojos.School.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(jooq.tables.pojos.School object) {
		return object.getSchoolId();
	}

	/**
	 * Fetch records that have <code>school_id IN (values)</code>
	 */
	public List<jooq.tables.pojos.School> fetchBySchoolId(Integer... values) {
		return fetch(School.SCHOOL.SCHOOL_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>school_id = value</code>
	 */
	public jooq.tables.pojos.School fetchOneBySchoolId(Integer value) {
		return fetchOne(School.SCHOOL.SCHOOL_ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<jooq.tables.pojos.School> fetchByName(String... values) {
		return fetch(School.SCHOOL.NAME, values);
	}

	/**
	 * Fetch records that have <code>type IN (values)</code>
	 */
	public List<jooq.tables.pojos.School> fetchByType(String... values) {
		return fetch(School.SCHOOL.TYPE, values);
	}

	/**
	 * Fetch records that have <code>total_students IN (values)</code>
	 */
	public List<jooq.tables.pojos.School> fetchByTotalStudents(Integer... values) {
		return fetch(School.SCHOOL.TOTAL_STUDENTS, values);
	}

	/**
	 * Fetch records that have <code>established_date IN (values)</code>
	 */
	public List<jooq.tables.pojos.School> fetchByEstablishedDate(Date... values) {
		return fetch(School.SCHOOL.ESTABLISHED_DATE, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public List<jooq.tables.pojos.School> fetchByDescription(String... values) {
		return fetch(School.SCHOOL.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>location_id IN (values)</code>
	 */
	public List<jooq.tables.pojos.School> fetchByLocationId(Integer... values) {
		return fetch(School.SCHOOL.LOCATION_ID, values);
	}

	/**
	 * Fetch records that have <code>image_id IN (values)</code>
	 */
	public List<jooq.tables.pojos.School> fetchByImageId(Integer... values) {
		return fetch(School.SCHOOL.IMAGE_ID, values);
	}
}
